# Generated by Django 3.2.5 on 2021-10-31 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0002_auto_20211022_2346'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListingBid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bids', models.IntegerField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listing.listing')),
            ],
            options={
                'verbose_name_plural': 'ListingBids',
            },
        ),
    ]
