# Generated by Django 3.2.5 on 2022-11-06 14:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('listing', '0003_listingbid'),
    ]

    operations = [
        migrations.AddField(
            model_name='listingbid',
            name='bidders',
            field=models.ManyToManyField(blank=True, related_name='bidders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='listing',
            name='image',
            field=models.ImageField(default='images/back.png', upload_to='static'),
        ),
    ]
