# Generated by Django 3.2.5 on 2022-11-13 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0004_auto_20221106_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listingbid',
            name='bids',
            field=models.IntegerField(blank=True),
        ),
    ]
