# Generated by Django 3.2.5 on 2022-11-13 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0005_alter_listingbid_bids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listingbid',
            name='bids',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
