# Generated by Django 3.2.5 on 2022-11-06 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0004_auto_20221106_1426'),
        ('userBids', '0002_auto_20221106_1515'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userbids',
            name='item',
        ),
        migrations.AddField(
            model_name='userbids',
            name='item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_item', to='listing.listing'),
            preserve_default=False,
        ),
    ]
