# Generated by Django 3.2.5 on 2022-11-06 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0004_auto_20221106_1426'),
        ('userBids', '0003_auto_20221106_1520'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userbids',
            name='item',
        ),
        migrations.AddField(
            model_name='userbids',
            name='item',
            field=models.ManyToManyField(related_name='user_item', to='listing.Listing'),
        ),
    ]
